[project]
name = "strata-fit-v6-imputation-py"
version = "0.1.0"
requires-python = ">=3.12"
dependencies = [
    "polars>=1.35.2",
    "pyarrow>=22.0.0",
    "vantage6>=4.13.1",
    "vantage6-algorithm-tools>=4.13.1",
]
